name: cafe_cirebon
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  search_page: ^2.3.0
  fluttertoast: ^8.2.2
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  loading_animation_widget: ^1.2.0+4
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

